// <auto-generated />
using System;
using Espada.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Espada.Db.Migrations
{
    [DbContext(typeof(EspadaDbContext))]
    [Migration("20260726044904_AddPersistenceConstraintsAndConcurrency")]
    partial class AddPersistenceConstraintsAndConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Espada.Domain.Aggregates.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactId");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ArchivedAtUtc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("CurrentRevisionId");

                    b.Property<int?>("CurrentRevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentRevisionNumber");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Artifacts_StatusId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Artifacts_WorkspaceId");

                    b.HasIndex("WorkspaceId", "Title")
                        .HasDatabaseName("IX_Artifacts_WorkspaceId_Title");

                    b.ToTable("Artifacts", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ArtifactRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactRevisionId");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("RevisionNumber");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_ArtifactRevisions_ArtifactId");

                    b.HasIndex("ArtifactId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtifactRevisions_ArtifactId_RevisionNumber");

                    b.ToTable("ArtifactRevisions", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ChunkId");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactId");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactRevisionId");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChunkBatchId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("ChunkNumber");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer")
                        .HasColumnName("StrategyId");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("StrategyVersion");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_Chunks_ArtifactId");

                    b.HasIndex("ArtifactRevisionId")
                        .HasDatabaseName("IX_Chunks_ArtifactRevisionId");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("IX_Chunks_ChunkBatchId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Chunks_WorkspaceId");

                    b.HasIndex("BatchId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_Chunks_ChunkBatchId_ChunkNumber");

                    b.ToTable("Chunks", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ChunkBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ChunkBatchId");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactId");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactRevisionId");

                    b.Property<int?>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("ChunkCount");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CompletedAtUtc");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("FailureReason");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("RequestedAtUtc");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartedAtUtc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer")
                        .HasColumnName("StrategyId");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("StrategyVersion");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_ChunkBatches_ArtifactId");

                    b.HasIndex("ArtifactRevisionId")
                        .HasDatabaseName("IX_ChunkBatches_ArtifactRevisionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ChunkBatches_StatusId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ChunkBatches_WorkspaceId");

                    b.HasIndex("ArtifactRevisionId", "Strategy", "StrategyVersion")
                        .HasDatabaseName("IX_ChunkBatches_Revision_Strategy_Version");

                    b.ToTable("ChunkBatches", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ChunkEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ChunkEmbeddingId");

                    b.Property<string>("ChunkContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ChunkContentHash");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChunkId");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("Dimensions");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.Property<string>("_modelIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ModelIdentifier");

                    b.Property<string>("_modelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModelVersion");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("IX_ChunkEmbeddings_ChunkId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ChunkEmbeddings_WorkspaceId");

                    b.HasIndex("ChunkId", "_modelIdentifier", "_modelVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_ChunkEmbeddings_ChunkId_ModelIdentifier_ModelVersion");

                    b.ToTable("ChunkEmbeddings", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ImportJobId");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactId");

                    b.Property<Guid?>("ArtifactRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ArtifactRevisionId");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CompletedAtUtc");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("RequestedAtUtc");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("StartedAtUtc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("IX_ImportJobs_SourceId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ImportJobs_StatusId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ImportJobs_WorkspaceId");

                    b.ToTable("ImportJobs", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceId");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ArchivedAtUtc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("Locator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Sources_StatusId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Sources_WorkspaceId");

                    b.HasIndex("WorkspaceId", "Locator")
                        .IsUnique()
                        .HasDatabaseName("UX_Sources_WorkspaceId_Locator");

                    b.ToTable("Sources", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("WorkspaceId");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ArchivedAtUtc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("StatusId");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("TypeId");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Workspaces_Name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Workspaces_StatusId");

                    b.ToTable("Workspaces", "Espada");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Artifact", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ArtifactRevision", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Chunk", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Domain.Aggregates.ArtifactRevision", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Domain.Aggregates.ChunkBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Espada.Domain.ValueObjects.SourceTextSpan", "SourceSpan", b1 =>
                        {
                            b1.Property<Guid>("ChunkId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Length")
                                .HasColumnType("integer")
                                .HasColumnName("SourceLength");

                            b1.Property<int>("Start")
                                .HasColumnType("integer")
                                .HasColumnName("SourceStart");

                            b1.HasKey("ChunkId");

                            b1.ToTable("Chunks", "Espada");

                            b1.WithOwner()
                                .HasForeignKey("ChunkId");
                        });

                    b.Navigation("SourceSpan");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ChunkBatch", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.ArtifactRevision", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ChunkEmbedding", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Chunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.ImportJob", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Domain.Aggregates.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Espada.Domain.ValueObjects.ImportFailure", "Failure", b1 =>
                        {
                            b1.Property<Guid>("ImportJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("FailureCode");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("varchar(4000)")
                                .HasColumnName("FailureReason");

                            b1.HasKey("ImportJobId");

                            b1.ToTable("ImportJobs", "Espada");

                            b1.WithOwner()
                                .HasForeignKey("ImportJobId");
                        });

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Espada.Domain.Aggregates.Source", b =>
                {
                    b.HasOne("Espada.Domain.Aggregates.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
