// <auto-generated />
using System;
using Espada.Db.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Espada.Db.Migrations
{
    [DbContext(typeof(SetupDbContext))]
    [Migration("20260728070102_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Espada")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Espada.Db.Models.ArtifactRevisions", b =>
                {
                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtifactRevisionId");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_ArtifactRevisions_ArtifactId");

                    b.HasIndex("ArtifactId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtifactRevisions_ArtifactId_RevisionNumber");

                    b.HasIndex("ArtifactId", "WorkspaceId");

                    b.ToTable("ArtifactRevisions", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ArtifactStatusTypes", b =>
                {
                    b.Property<int>("ArtifactStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ArtifactStatusTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtifactStatusTypes_Name");

                    b.ToTable("ArtifactStatusTypes", "Espada");

                    b.HasData(
                        new
                        {
                            ArtifactStatusTypeId = 1,
                            Name = "Active"
                        },
                        new
                        {
                            ArtifactStatusTypeId = 2,
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.ArtifactTypes", b =>
                {
                    b.Property<int>("ArtifactTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ArtifactTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ArtifactTypes_Name");

                    b.ToTable("ArtifactTypes", "Espada");

                    b.HasData(
                        new
                        {
                            ArtifactTypeId = 1,
                            Name = "Text"
                        },
                        new
                        {
                            ArtifactTypeId = 2,
                            Name = "Markdown"
                        },
                        new
                        {
                            ArtifactTypeId = 3,
                            Name = "File"
                        },
                        new
                        {
                            ArtifactTypeId = 4,
                            Name = "WebPage"
                        },
                        new
                        {
                            ArtifactTypeId = 5,
                            Name = "Conversation"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.Artifacts", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentRevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ArtifactId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_Artifacts_StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Artifacts_WorkspaceId");

                    b.HasIndex("WorkspaceId", "Title")
                        .HasDatabaseName("IX_Artifacts_WorkspaceId_Title");

                    b.ToTable("Artifacts", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.BillingCustomers", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastProviderEventAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PaymentFailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderCustomerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("ProviderCustomerId")
                        .IsUnique();

                    b.ToTable("BillingCustomers", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.Bindings", b =>
                {
                    b.Property<Guid>("BindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Agent")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepositoryCanonicalUri")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("RepositoryRelativePathPrefix")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("BindingId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ArtifactRevisionId", "WorkspaceId");

                    b.HasIndex("ProjectId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "ArtifactRevisionId")
                        .HasDatabaseName("IX_Bindings_WorkspaceId_ArtifactRevisionId");

                    b.HasIndex("TaskId", "ProjectId", "WorkspaceId");

                    b.ToTable("Bindings", "Espada", t =>
                        {
                            t.HasCheckConstraint("CK_Bindings_TaskRequiresProject", "\"TaskId\" IS NULL OR \"ProjectId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkBatchStatusTypes", b =>
                {
                    b.Property<int>("ChunkBatchStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ChunkBatchStatusTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ChunkBatchStatusTypes_Name");

                    b.ToTable("ChunkBatchStatusTypes", "Espada");

                    b.HasData(
                        new
                        {
                            ChunkBatchStatusTypeId = 1,
                            Name = "Requested"
                        },
                        new
                        {
                            ChunkBatchStatusTypeId = 2,
                            Name = "Running"
                        },
                        new
                        {
                            ChunkBatchStatusTypeId = 3,
                            Name = "Succeeded"
                        },
                        new
                        {
                            ChunkBatchStatusTypeId = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkBatches", b =>
                {
                    b.Property<Guid>("ChunkBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("StrategyId")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ChunkBatchId");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_ChunkBatches_ArtifactId");

                    b.HasIndex("ArtifactRevisionId")
                        .HasDatabaseName("IX_ChunkBatches_ArtifactRevisionId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_ChunkBatches_StatusId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ChunkBatches_WorkspaceId");

                    b.HasIndex("ArtifactRevisionId", "StrategyId", "StrategyVersion")
                        .HasDatabaseName("IX_ChunkBatches_Revision_Strategy_Version");

                    b.ToTable("ChunkBatches", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkEmbeddingVectors", b =>
                {
                    b.Property<Guid>("ChunkEmbeddingId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector");

                    b.HasKey("ChunkEmbeddingId");

                    b.ToTable("ChunkEmbeddingVectors", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkEmbeddings", b =>
                {
                    b.Property<Guid>("ChunkEmbeddingId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ChunkEmbeddingId");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("IX_ChunkEmbeddings_ChunkId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ChunkEmbeddings_WorkspaceId");

                    b.HasIndex("ChunkId", "ModelIdentifier", "ModelVersion")
                        .IsUnique()
                        .HasDatabaseName("UX_ChunkEmbeddings_ChunkId_ModelIdentifier_ModelVersion");

                    b.ToTable("ChunkEmbeddings", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkingStrategyTypes", b =>
                {
                    b.Property<int>("ChunkingStrategyTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ChunkingStrategyTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ChunkingStrategyTypes_Name");

                    b.ToTable("ChunkingStrategyTypes", "Espada");

                    b.HasData(
                        new
                        {
                            ChunkingStrategyTypeId = 1,
                            Name = "FixedSize"
                        },
                        new
                        {
                            ChunkingStrategyTypeId = 2,
                            Name = "Recursive"
                        },
                        new
                        {
                            ChunkingStrategyTypeId = 3,
                            Name = "Markdown"
                        },
                        new
                        {
                            ChunkingStrategyTypeId = 4,
                            Name = "Semantic"
                        },
                        new
                        {
                            ChunkingStrategyTypeId = 5,
                            Name = "Code"
                        },
                        new
                        {
                            ChunkingStrategyTypeId = 6,
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.Chunks", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("StrategyId")
                        .HasColumnType("integer");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ChunkId");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("IX_Chunks_ArtifactId");

                    b.HasIndex("ArtifactRevisionId")
                        .HasDatabaseName("IX_Chunks_ArtifactRevisionId");

                    b.HasIndex("ChunkBatchId")
                        .HasDatabaseName("IX_Chunks_ChunkBatchId");

                    b.HasIndex("StrategyId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Chunks_WorkspaceId");

                    b.HasIndex("ChunkBatchId", "ChunkNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Chunks_ChunkBatchId_ChunkNumber");

                    b.ToTable("Chunks", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ImportJobs", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChunkBatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("ParsedBlobHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RawBlobHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ImportJobId");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("IX_ImportJobs_SourceId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_ImportJobs_StatusId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_ImportJobs_WorkspaceId");

                    b.HasIndex("WorkspaceId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ImportJobs_WorkspaceId_IdempotencyKey");

                    b.ToTable("ImportJobs", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ImportStatusTypes", b =>
                {
                    b.Property<int>("ImportStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ImportStatusTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ImportStatusTypes_Name");

                    b.ToTable("ImportStatusTypes", "Espada");

                    b.HasData(
                        new
                        {
                            ImportStatusTypeId = 1,
                            Name = "Requested"
                        },
                        new
                        {
                            ImportStatusTypeId = 2,
                            Name = "Running"
                        },
                        new
                        {
                            ImportStatusTypeId = 3,
                            Name = "Succeeded"
                        },
                        new
                        {
                            ImportStatusTypeId = 4,
                            Name = "Failed"
                        },
                        new
                        {
                            ImportStatusTypeId = 5,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.IngestionJobs", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FailureCategory")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ImportJobId");

                    b.HasIndex("Status", "AvailableAtUtc", "LeaseExpiresAtUtc");

                    b.ToTable("IngestionJobs", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.InstructionRules", b =>
                {
                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtifactRevisionId", "RuleKey")
                        .HasName("PK_InstructionRules_ArtifactRevisionId_RuleKey");

                    b.HasIndex("ArtifactRevisionId", "Kind");

                    b.ToTable("InstructionRules", "Espada", t =>
                        {
                            t.HasCheckConstraint("CK_InstructionRules_Kind", "\"Kind\" = 'instruction'");
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.MemoryMetadataRecords", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ClientIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SessionIdentity")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("SupersededMemoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UserConfirmed")
                        .HasColumnType("boolean");

                    b.HasKey("MemoryId");

                    b.HasIndex("SupersededMemoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_MemoryMetadata_SupersededMemoryId")
                        .HasFilter("\"SupersededMemoryId\" IS NOT NULL");

                    b.HasIndex("ArtifactId", "ArtifactRevisionId")
                        .IsUnique()
                        .HasDatabaseName("UX_MemoryMetadata_ArtifactId_ArtifactRevisionId");

                    b.HasIndex("ArtifactRevisionId", "ArtifactId", "Kind");

                    b.ToTable("MemoryMetadata", "Espada", t =>
                        {
                            t.HasCheckConstraint("CK_MemoryMetadata_Kind", "\"Kind\" = 'memory'");
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.OrganizationMemberships", b =>
                {
                    b.Property<Guid>("OrganizationMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("OrganizationMembershipId");

                    b.HasIndex("OrganizationId", "Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("UX_OrganizationMemberships_OrganizationId_Issuer_Subject");

                    b.ToTable("OrganizationMemberships", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.Organizations", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OrganizationId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Organizations_Name");

                    b.ToTable("Organizations", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.OutboxMessages", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAtUtc", "AvailableAtUtc");

                    b.ToTable("OutboxMessages", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.PaymentEvents", b =>
                {
                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ApiVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ProviderCreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ProviderEventId");

                    b.HasIndex("Status", "AvailableAtUtc", "LeaseExpiresAtUtc");

                    b.ToTable("PaymentEvents", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.PolicyRules", b =>
                {
                    b.Property<Guid>("ArtifactRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Enforcement")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtifactRevisionId", "RuleKey")
                        .HasName("PK_PolicyRules_ArtifactRevisionId_RuleKey");

                    b.HasIndex("ArtifactRevisionId", "Kind");

                    b.ToTable("PolicyRules", "Espada", t =>
                        {
                            t.HasCheckConstraint("CK_PolicyRules_Kind", "\"Kind\" = 'policy'");
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.Projects", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalRemoteUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.PrimitiveCollection<string[]>("LocalAliases")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId");

                    b.HasIndex("WorkspaceId", "CanonicalRemoteUri")
                        .IsUnique()
                        .HasDatabaseName("UX_Projects_WorkspaceId_CanonicalRemoteUri");

                    b.ToTable("Projects", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.SourceStatusTypes", b =>
                {
                    b.Property<int>("SourceStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SourceStatusTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_SourceStatusTypes_Name");

                    b.ToTable("SourceStatusTypes", "Espada");

                    b.HasData(
                        new
                        {
                            SourceStatusTypeId = 1,
                            Name = "Active"
                        },
                        new
                        {
                            SourceStatusTypeId = 2,
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.SourceTypes", b =>
                {
                    b.Property<int>("SourceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SourceTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_SourceTypes_Name");

                    b.ToTable("SourceTypes", "Espada");

                    b.HasData(
                        new
                        {
                            SourceTypeId = 1,
                            Name = "File"
                        },
                        new
                        {
                            SourceTypeId = 2,
                            Name = "WebPage"
                        },
                        new
                        {
                            SourceTypeId = 3,
                            Name = "PlainText"
                        },
                        new
                        {
                            SourceTypeId = 4,
                            Name = "Conversation"
                        },
                        new
                        {
                            SourceTypeId = 5,
                            Name = "Connector"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.Sources", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DefinitionJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Locator")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("SourceId");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_Sources_StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Sources_WorkspaceId");

                    b.HasIndex("WorkspaceId", "Locator")
                        .IsUnique()
                        .HasDatabaseName("UX_Sources_WorkspaceId_Locator");

                    b.ToTable("Sources", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.Tasks", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId", "WorkspaceId");

                    b.HasIndex("WorkspaceId", "ProjectId", "Status")
                        .HasDatabaseName("IX_Tasks_WorkspaceId_ProjectId_Status");

                    b.ToTable("Tasks", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.UsageLedgerEntries", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("EntryId");

                    b.HasIndex("WorkspaceId", "Metric", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("UsageLedgerEntries", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.UsageReconciliationOutbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("LedgerEntryId")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAtUtc", "LeaseExpiresAtUtc");

                    b.ToTable("UsageReconciliationOutbox", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.WorkspaceMemberships", b =>
                {
                    b.Property<Guid>("WorkspaceMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkspaceMembershipId");

                    b.HasIndex("WorkspaceId", "Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.WorkspaceStatusTypes", b =>
                {
                    b.Property<int>("WorkspaceStatusTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("WorkspaceStatusTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkspaceStatusTypes_Name");

                    b.ToTable("WorkspaceStatusTypes", "Espada");

                    b.HasData(
                        new
                        {
                            WorkspaceStatusTypeId = 1,
                            Name = "Active"
                        },
                        new
                        {
                            WorkspaceStatusTypeId = 2,
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.WorkspaceTypes", b =>
                {
                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("WorkspaceTypeId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkspaceTypes_Name");

                    b.ToTable("WorkspaceTypes", "Espada");

                    b.HasData(
                        new
                        {
                            WorkspaceTypeId = 1,
                            Name = "Personal"
                        },
                        new
                        {
                            WorkspaceTypeId = 2,
                            Name = "Team"
                        },
                        new
                        {
                            WorkspaceTypeId = 3,
                            Name = "Organization"
                        });
                });

            modelBuilder.Entity("Espada.Db.Models.Workspaces", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WorkspaceId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Workspaces_Name");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("IX_Workspaces_StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Workspaces", "Espada");
                });

            modelBuilder.Entity("Espada.Db.Models.ArtifactRevisions", b =>
                {
                    b.HasOne("Espada.Db.Models.Artifacts", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId", "WorkspaceId")
                        .HasPrincipalKey("ArtifactId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Artifacts", b =>
                {
                    b.HasOne("Espada.Db.Models.ArtifactStatusTypes", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ArtifactTypes", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.BillingCustomers", b =>
                {
                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Bindings", b =>
                {
                    b.HasOne("Espada.Db.Models.Organizations", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId", "WorkspaceId")
                        .HasPrincipalKey("ArtifactRevisionId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.Projects", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId")
                        .HasPrincipalKey("ProjectId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Espada.Db.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "ProjectId", "WorkspaceId")
                        .HasPrincipalKey("TaskId", "ProjectId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkBatches", b =>
                {
                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ChunkBatchStatusTypes", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ChunkingStrategyTypes", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkEmbeddingVectors", b =>
                {
                    b.HasOne("Espada.Db.Models.ChunkEmbeddings", null)
                        .WithOne()
                        .HasForeignKey("Espada.Db.Models.ChunkEmbeddingVectors", "ChunkEmbeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.ChunkEmbeddings", b =>
                {
                    b.HasOne("Espada.Db.Models.Chunks", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Chunks", b =>
                {
                    b.HasOne("Espada.Db.Models.Artifacts", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ChunkBatches", null)
                        .WithMany()
                        .HasForeignKey("ChunkBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ChunkingStrategyTypes", null)
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Espada.Db.Models.SourceSpanModel", "SourceSpan", b1 =>
                        {
                            b1.Property<Guid>("ChunksChunkId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Length")
                                .HasColumnType("integer")
                                .HasColumnName("SourceLength");

                            b1.Property<int>("Start")
                                .HasColumnType("integer")
                                .HasColumnName("SourceStart");

                            b1.HasKey("ChunksChunkId");

                            b1.ToTable("Chunks", "Espada");

                            b1.WithOwner()
                                .HasForeignKey("ChunksChunkId");
                        });

                    b.Navigation("SourceSpan");
                });

            modelBuilder.Entity("Espada.Db.Models.ImportJobs", b =>
                {
                    b.HasOne("Espada.Db.Models.Sources", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.ImportStatusTypes", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Espada.Db.Models.ImportFailureModel", "Failure", b1 =>
                        {
                            b1.Property<Guid>("ImportJobsImportJobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("FailureCode");

                            b1.Property<string>("Reason")
                                .HasMaxLength(4000)
                                .HasColumnType("varchar(4000)")
                                .HasColumnName("FailureReason");

                            b1.HasKey("ImportJobsImportJobId");

                            b1.ToTable("ImportJobs", "Espada");

                            b1.WithOwner()
                                .HasForeignKey("ImportJobsImportJobId");
                        });

                    b.Navigation("Failure");
                });

            modelBuilder.Entity("Espada.Db.Models.IngestionJobs", b =>
                {
                    b.HasOne("Espada.Db.Models.ImportJobs", null)
                        .WithMany()
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.InstructionRules", b =>
                {
                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId", "Kind")
                        .HasPrincipalKey("ArtifactRevisionId", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.MemoryMetadataRecords", b =>
                {
                    b.HasOne("Espada.Db.Models.MemoryMetadataRecords", null)
                        .WithMany()
                        .HasForeignKey("SupersededMemoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId", "ArtifactId", "Kind")
                        .HasPrincipalKey("ArtifactRevisionId", "ArtifactId", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.OrganizationMemberships", b =>
                {
                    b.HasOne("Espada.Db.Models.Organizations", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.PolicyRules", b =>
                {
                    b.HasOne("Espada.Db.Models.ArtifactRevisions", null)
                        .WithMany()
                        .HasForeignKey("ArtifactRevisionId", "Kind")
                        .HasPrincipalKey("ArtifactRevisionId", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Projects", b =>
                {
                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Sources", b =>
                {
                    b.HasOne("Espada.Db.Models.SourceStatusTypes", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.SourceTypes", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Tasks", b =>
                {
                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.Projects", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId")
                        .HasPrincipalKey("ProjectId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.UsageLedgerEntries", b =>
                {
                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.UsageReconciliationOutbox", b =>
                {
                    b.HasOne("Espada.Db.Models.UsageLedgerEntries", null)
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.WorkspaceMemberships", b =>
                {
                    b.HasOne("Espada.Db.Models.Workspaces", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Espada.Db.Models.Workspaces", b =>
                {
                    b.HasOne("Espada.Db.Models.WorkspaceStatusTypes", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Espada.Db.Models.WorkspaceTypes", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
