<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Espada.Tests.E2E</RootNamespace>
        <AssemblyName>Espada.Tests.E2E</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Espada.Tests.Common\Espada.Tests.Common.csproj" />
        <ProjectReference Include="..\..\src\Espada.Api.Contracts\Espada.Api.Contracts.csproj" />
        <ProjectReference Include="..\..\src\Espada.Api\Espada.Api.csproj" />
        <ProjectReference Include="..\..\src\Espada.Db\Espada.Db.csproj" />
        <ProjectReference Include="..\..\src\Espada.Infrastructure\Espada.Infrastructure.csproj" />
    </ItemGroup>

</Project>