<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Espada.Tests.Integration</RootNamespace>
        <AssemblyName>Espada.Tests.Integration</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Espada.Tests.Common\Espada.Tests.Common.csproj"/>
        <ProjectReference Include="..\..\src\Espada.Application\Espada.Application.csproj"/>
        <ProjectReference Include="..\..\src\Espada.Db\Espada.Db.csproj"/>
        <ProjectReference Include="..\..\src\Espada.Domain\Espada.Domain.csproj"/>
        <ProjectReference Include="..\..\src\Espada.Infrastructure\Espada.Infrastructure.csproj"/>
    </ItemGroup>

</Project>